routes/web.php
<?php



Route::get('/', function () {
    dd(1);
});

Route::get('/', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('/', 'Auth\LoginController@login');
Route::post('/logout', 'Auth\LoginController@logout')->name('logout');

Route::group(
    [
        'prefix' => 'employees',
        'as' => 'employees.',
        'namespace' => 'Employees',
        'middleware' => ['auth', 'mustByActive'],
    ],
    function () {
        Route::get('/contract/autocomplete', 'ContractController@autocomplete')->name('contract.autocomplete');
        Route::get('/client/autocomplete', 'ClientController@autocomplete')->name('client.autocomplete');
        Route::get('/car/autocomplete', 'CarController@autocomplete')->name('car.autocomplete');
        Route::get('/car-model', 'CarModelController@byMark')->name('carModel.byMark');

        Route::group(
            [
                'prefix' => 'discount-card',
                'as' => 'discountCard.',
            ],
            function () {
                Route::get('', 'DiscountCardController@list')->name('list');
                Route::get('/create', 'DiscountCardController@createForm')->name('create');
                Route::post('/create', 'DiscountCardController@create');
                Route::get('/check', 'DiscountCardController@check')->name('check');

                Route::get('/{discountCard}/edit', 'DiscountCardController@editForm')->name('edit');
                Route::put('/{discountCard}/edit', 'DiscountCardController@edit');
                Route::get('/{discountCard}/edit-disc', 'DiscountCardController@editDiscForm')->name('editDisc');
                Route::put('/{discountCard}/edit-disc', 'DiscountCardController@editDisc');

                Route::get('/{discountCard}', 'DiscountCardController@show')->name('show');
            }
        );

        Route::group(
            [
                'prefix' => 'cafe',
                'as' => 'cafe.'
            ],
            function () {
                Route::get('/sale', 'CafeController@createSaleForm')->name('createSale');
                Route::post('/sale', 'CafeController@createSale');
            }
        );

        Route::group(
            [
                'prefix' => 'order',
                'as' => 'order.',
                'namespace' => 'Order',
            ],
            function () {
                Route::get('', 'OrderController@list')->name('list');

                Route::get('/service-history', 'ServiceHistoryController@list')->name('serviceHistory');

                Route::get('/check-new-order', 'PaymentController@checkNewOrder')->name('checkNewOrder');
                Route::get('/user-register', 'ClientRegisterController@registerForm')->name('clientRegister');
                Route::post('/user-register', 'ClientRegisterController@register');

                Route::get('/{car}/{client}/ordering', 'OrderingController@orderingForm')->name('ordering');
                Route::post('/{car}/{client}/ordering', 'OrderingController@ordering');

                Route::get('/{order}', 'OrderingController@show')->name('show');

                Route::get('/{order}/edit-works', 'OrderingController@editWorksForm')->name('editWorks');
                Route::patch('/{order}/edit-works', 'OrderingController@editWorks');

                Route::patch('/{order}/admin-comment', 'OrderingController@comment')->name('adminComment');

                Route::get('/list/payment', 'PaymentController@list')->name('payment.list');
                Route::get('/{order}/payment', 'PaymentController@paymentForm')->name('payment');
                Route::post('/{order}/payment', 'PaymentController@payment');
                Route::put('/{order}/repayment', 'PaymentController@repayment')->name('repayment');
                Route::post('/{order}/payment-refusal', 'PaymentController@refusal')->name('paymentRefusal');

                Route::get('/list/overdrive', 'OverdriveController@list')->name('overdrive.list');
                Route::get('/{order}/appoint-team', 'AppointTeamController@appointTeamForm')->name('appointTeam');
                Route::patch('/{order}/appoint-team', 'AppointTeamController@appointTeam');

                Route::get('/{order}/reassign-team', 'AppointTeamController@reassignTeamForm')->name('reassignTeam');
                Route::patch('/{order}/reassign-team', 'AppointTeamController@reassignTeam');

                Route::patch('/{order}/comment', 'PaymentController@comment')->name('comment');

                Route::get('/{order}/fine', 'FineController@createForm')->name('createFine');
                Route::post('/{order}/fine', 'FineController@create');

                Route::get('/{order}/cross', 'FineController@crossForm')->name('cross');
                Route::post('/{order}/cross', 'FineController@cross');

                Route::patch('/{order}/executed', 'OrderingController@executed')->name('executed');

                Route::get('/fine/{fine}/disable', 'FineController@disableForm')->name('disableFine');
                Route::put('/fine/{fine}/disable', 'FineController@disable');
            }
        );

        Route::group(
            [
                'prefix' => 'teams',
                'as' => 'teams.',
            ],
            function () {
                Route::get('', 'TeamController@list')->name('list');
                Route::get('/create', 'TeamController@createForm')->name('create');
                Route::post('/create', 'TeamController@create');
                Route::get('/{team}', 'TeamController@show')->name('show');
                Route::get('/{team}/edit', 'TeamController@editForm')->name('edit');
                Route::put('/{team}/edit', 'TeamController@edit');
                Route::delete('/{team}/delete', 'TeamController@delete')->name('delete');
            }
        );

        Route::group(
            [
                'prefix' => 'balance',
                'as' => 'balance.',
            ],
            function () {
                Route::get('', 'BalanceController@common')->name('common');
            }
        );

        Route::group(
            [
                'prefix' => 'accrual',
                'as' => 'accrual.',
                'namespace' => 'Accrual',
            ],
            function () {
                Route::get('', 'AccrualController@common')->name('common');
                Route::get('personal-fine', 'PersonalFineController@list')->name('personalFines');
                Route::get('team-fine', 'TeamFineController@list')->name('teamFines');
                Route::get('employees', 'EmployeesController@list')->name('employees');
            }
        );

        Route::group(
            [
                'prefix' => 'washer',
                'as' => 'washer.',
                'namespace' => 'Washer',
            ],
            function () {
                Route::get('', 'WasherController@list')->name('list');
                Route::get('/{user}', 'WasherController@show')->name('show');

                Route::get('/{user}/fine', 'PersonalFineController@createForm')->name('createFine');
                Route::post('/{user}/fine', 'PersonalFineController@create');

                Route::get('/personal-fine/{fine}', 'PersonalFineController@show')->name('showPersonalFine');
                Route::get('/personal-fine/{fine}/disable', 'PersonalFineController@disableForm')->name('disablePersonalFine');
                Route::put('/personal-fine/{fine}/disable', 'PersonalFineController@disable');
                Route::get('/{user}/personal-fines', 'PersonalFineController@list')->name('personalFines');
                Route::get('/{user}/team-fines', 'TeamFineController@list')->name('teamFines');
                Route::get('/{user}/salary-breakdown', 'SalaryBreakdownController@index')->name('salaryBreakdown');
            }
        );
    }
);

Route::group(
    [
        'prefix' => 'super_admin',
        'as' => 'superAdmin.',
        'namespace' => 'SuperAdmin',
        'middleware' => ['auth', 'mustByActive', App\Http\Middleware\SuperAdmin::class],
    ],
    function () {
        Route::get('/', 'HomeController@index')->name('home');

        Route::group(
            [
                'prefix' => 'fine',
                'as' => 'fine.',
                'namespace' => 'Fine',
            ],
            function () {
                Route::get('payment-refusal-fine-size', 'PaymentRefusalFineSizeController@form')->name('paymentRefusalFineSize');
                Route::put('payment-refusal-fine-size', 'PaymentRefusalFineSizeController@change');
            }
        );

        Route::group(
            [
                'prefix' => 'service_center',
                'as' => 'serviceCenter.'
            ],
            function () {
                Route::get('', 'ServiceCentersController@list')->name('list');
                Route::get('/create', 'ServiceCentersController@createForm')->name('create');
                Route::post('/create', 'ServiceCentersController@create');
                Route::get('/{serviceCenter}', 'ServiceCentersController@show')->name('show');
                Route::get('/{serviceCenter}/edit', 'ServiceCentersController@editForm')->name('edit');
                Route::put('/{serviceCenter}/edit', 'ServiceCentersController@edit');
                Route::delete('/{serviceCenter}/delete', 'ServiceCentersController@delete')->name('delete');
            }
        );

        Route::group(
            [
                'prefix' => 'car_wash',
                'as' => 'carWash.',
                'namespace' => 'CarWash',
            ],
            function () {
                Route::group(
                    [
                        'prefix' => 'works',
                        'as' => 'works.',
                    ],
                    function () {
                        Route::get('', 'WorksController@index')->name('list');

app/Http/Controllers/Employees/Accrual/AccrualController.php
<?php

namespace App\Http\Controllers\Employees\Accrual;

use App\Entity\ServiceCenter;
use App\Entity\User\Role;
use App\Entity\User\User;
use App\Http\Controllers\Controller;
use App\Services\AccrualService;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class AccrualController extends Controller
{
    public function __construct()
    {
        $this->middleware(['auth', 'can:manage-accrual']);
    }

    public function common()
    {
        $pageTitle = trans('accrual.page.common.header');
        $commonAccrual = $this->getService()->common();

        return view('employees.accrual.common', compact('pageTitle', 'commonAccrual'));
    }

    private function getService(): AccrualService
    {
        /** @var User $user */
        $user = Auth::user();
        /** @var ServiceCenter $serviceCenter */
        $serviceCenter = $user->serviceCenter;
        return new AccrualService($serviceCenter);
    }
}

app/Http/Controllers/Employees/Accrual/EmployeesController.php
<?php

namespace App\Http\Controllers\Employees\Accrual;

use App\Entity\ServiceCenter;
use App\Entity\User\Role;
use App\Entity\User\User;
use App\Http\Controllers\Controller;
use App\Services\AccrualService;
use App\Services\Dto\DateRangeDto;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class EmployeesController extends Controller
{
    public function __construct()
    {
        $this->middleware(['auth', 'can:manage-accrual']);
    }

    public function list(Request $request)
    {
        $pageTitle = trans('accrual.page.employees.header');
        $dataRange = new DateRangeDto($request->get('range'));
        $accrualCollection = $this->getService()->employeesSalary($dataRange, Auth::user());

        return view('employees.accrual.employees', compact('pageTitle', 'accrualCollection', 'dataRange'));
    }

    private function getService(): AccrualService
    {
        /** @var User $user */
        $user = Auth::user();
        /** @var ServiceCenter $serviceCenter */
        $serviceCenter = $user->serviceCenter;
        return new AccrualService($serviceCenter);
    }
}

app/Http/Controllers/Employees/Accrual/PersonalFineController.php
<?php

namespace App\Http\Controllers\Employees\Accrual;

use App\Entity\ServiceCenter;
use App\Entity\User\Fine\PersonalFine;
use App\Entity\User\User;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;

class PersonalFineController extends Controller
{
    public function __construct()
    {
        $this->middleware(['auth', 'can:manage-personal-fines']);
    }

    public function list()
    {
        $pageTitle = trans('personalFine.page.list.header');

        /** @var User $user */
        $user = Auth::user();
        /** @var ServiceCenter $serviceCenter */
        $serviceCenter = $user->serviceCenter;
        $personalFines = PersonalFine::with(['user', 'user.serviceCenter'])->byServiceCenter($serviceCenter)->orderByDesc('id')->paginate(20);

        return view('employees.accrual.personalFines', compact('pageTitle', 'personalFines'));
    }
}

app/Http/Controllers/Employees/Accrual/TeamFineController.php
<?php

namespace App\Http\Controllers\Employees\Accrual;

use App\Entity\ServiceCenter;
use App\Entity\User\Fine\TeamFine;
use App\Entity\User\User;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;

class TeamFineController extends Controller
{
    public function __construct()
    {
        $this->middleware(['auth', 'can:manage-team-fines']);
    }

    public function list()
    {
        $pageTitle = trans('personalFine.page.list.header');

        /** @var User $user */
        $user = Auth::user();
        /** @var ServiceCenter $serviceCenter */
        $serviceCenter = $user->serviceCenter;

        $teamFines = TeamFine::with('users', 'order')->byServiceCenter($serviceCenter)->orderByDesc('id')->paginate(20);

        return view('employees.accrual.teamFines', compact('pageTitle', 'teamFines'));
    }
}

app/Http/Controllers/Employees/BalanceController.php
<?php

namespace App\Http\Controllers\Employees;

use App\Entity\User\User;
use App\Http\Controllers\Controller;
use App\Services\BalanceService;
use App\Services\Dto\DateRangeLastMonthDto;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class BalanceController extends Controller
{
    public function __construct()
    {
        $this->middleware(['auth', 'can:manage-balance']);
    }

    public function common(Request $request)
    {
        $pageTitle = trans('balance.page.common.header');

        /** @var User $user */
        $user = Auth::user();
        $service = new BalanceService($user->serviceCenter);

        $dataRange = new DateRangeLastMonthDto($request->get('range'));
        $balance = $service->common(
            $dataRange,
            $request->get('payment'),
            $request->get('point'),
            count($request->only(['range', 'payment', 'point'])) == 0
        );


        return view('employees.balance.common', compact('pageTitle', 'balance', 'dataRange'));
    }
}

app/Http/Controllers/Employees/CafeController.php
<?php

namespace App\Http\Controllers\Employees;

use App\Entity\Cafe\Sale;
use App\Entity\Cafe\SaleType;
use App\Entity\User\User;
use App\Http\Controllers\Controller;
use App\Http\Requests\Cafe\CreateSaleRequest;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class CafeController extends Controller
{
    public function __construct()
    {
        $this->middleware(['auth', 'can:manage-sale-cafe']);
    }

    public function createSaleForm(Request $request)
    {
        $pageTitle = trans('cafe.page.createSale.header');

        $saleTypes = SaleType::active()->orderBy('name')->orderBy('id')->get();
        $sale = new Sale();

        return view('employees.cafe.createSale', compact('pageTitle', 'saleTypes', 'sale'));
    }

    public function createSale(CreateSaleRequest $request)
    {
        /** @var User $user */
        $user = Auth::user();
        Sale::register(
            $request->get('sum'),
            $request->get('sale-type'),
            $request->get('payment-type'),
            $user,
            $user->serviceCenter
        );

        return redirect()
            ->to(route('employees.cafe.createSale'))
            ->with('success', trans('cafe.message.successCreateSale'));
    }
}

app/Http/Controllers/Employees/CarController.php
<?php

namespace App\Http\Controllers\Employees;

use App\Entity\Car;
use App\Http\Controllers\Controller;
use App\Http\Resources\CarAutocomplete;
use Illuminate\Http\Request;

class CarController extends Controller
{
    public function __construct()
    {
        $this->middleware(['auth', 'can:manage-order']);
    }

    public function autocomplete(Request $request)
    {
        $value = $request->get('value');
        $cars = Car::with('clients', 'carModel', 'carModel.mark')
            ->where('number', 'like', $value . '%')
            ->limit(20)
            ->get();

        return CarAutocomplete::collection($cars);
    }
}

app/Http/Controllers/Employees/CarModelController.php
<?php

namespace App\Http\Controllers\Employees;

use App\Entity\Car;
use App\Entity\CarModel;
use App\Http\Controllers\Controller;
use App\Http\Resources\CarModel as CarModelResources;
use Illuminate\Http\Request;

class CarModelController extends Controller
{
    public function __construct()
    {
        $this->middleware(['auth', 'can:manage-order']);
    }

    public function byMark(Request $request)
    {
        $markId = intval($request->get('mark'));

        $carModels = CarModel::forMark($markId)->get();

        return CarModelResources::collection($carModels);
    }
}

resources/views/employees/order/list.blade.php
@extends('employees.layouts.admin')

@section('content')

    <form method="GET" action="{{ route('employees.order.list') }}">
        <input type="hidden" name="status" value="{{ request('status') }}">
        @include('employees.order.partials._nav', ['statuses' => $statuses, 'currentStatus' => $status])
    </form>

    @if(!$teamExist)
        @include('partials.flash._template', ['type' => 'warning', 'message' => __('order.notFoundTeam') ])
    @endif

    <p>
        <a href="{{ route('employees.order.clientRegister') }}" class="btn btn-success">
            {{ __('order.action.create') }}
        </a>
    </p>

    <div class="card orders-list">
        <div class="list">
            @forelse($orders as $order)
                <div class="list__item">
                    <p class="list__header">
                        <a href="{{ route('employees.order.show', $order) }}">
                            {{ __('order.orderTitle', ['num' => $order->id]) }}
                        </a>
                    </p>
                    <p class="list__attribute attribute">
                        <span class="attribute__name">
                            {{ __('order.field.status') }}:
                        </span>
                        <span class="attribute__value">
                             @include('employees.order.partials._status', ['order' => $order])
                        </span>
                    </p>
                    <p class="list__attribute attribute">
                        <span class="attribute__name">
                            {{ __('order.field.teamName') }}:
                        </span>
                        <span class="attribute__value">
                            {{ $order->team_name }}
                        </span>
                    </p>
                    <p class="list__attribute attribute">
                        <span class="attribute__name">
                            {{ __('order.field.key') }}:
                        </span>
                        <span class="attribute__value">
                            {{ $order->number_key }}
                        </span>
                    </p>
                    <p class="list__attribute attribute">
                        <span class="attribute__name">
                            {{ __('order.field.number') }}:
                        </span>
                        <span class="attribute__value">
                            {{ $order->car->number }}
                            {{ $order->car->carMark->name }}
                            {{ $order->car->carModel->name }}
                        </span>
                    </p>
                    <p class="list__attribute attribute">
                        <span class="attribute__name">
                            {{ __('order.field.phone') }}:
                        </span>
                        <span class="attribute__value">
                            {{ phoneFormat($order->client->phone) }}
                        </span>
                    </p>
                    <p class="list__attribute attribute">
                        <span class="attribute__name">
                            {{ __('order.field.date') }}:
                        </span>
                        <span class="attribute__value">
                            {{ dataTimeFormat($order->created_at) }}
                        </span>
                    </p>
                    @if (isset($order->admin_comment))
                        <p class="list__attribute attribute">
                            <span class="attribute__name">
                                {{ __('order.field.adminComment') }}
                            </span>
                            <span class="attribute__value">
                                {{ $order->admin_comment }}
                            </span>
                        </p>
                    @endif
                </div>
            @empty
                <div class="p-3">
                    {{ __('order.notExist') }}
                </div>
            @endforelse
        </div>
    </div>
@endsection

resources/views/employees/order/show.blade.php
@extends('employees.layouts.admin')


@section('content')

    <div class="d-flex flex-row mb-3">
        @if ($order->isExecute() || $order->isQueue())
            <a href="{{ route('employees.order.editWorks', ['order' => $order]) }}" class="btn btn-success mr-1">
                {{ __('order.action.editWorks') }}
            </a>
        @endif

        @if ($order->isExecute() && $order->hasTemporaryTeam())
            <button class="btn btn-success mr-1" data-toggle="modal" data-target="#confirmExecute">
                {{ __('order.action.executed') }}
            </button>
            @include(
                'partials.modal.confirm',
                [
                    'target' => "confirmExecute",
                    'body' => __('order.confirm.execute'),
                    'action' => route('employees.order.executed', $order),
                    'method' => 'PATCH'
                ]
            )
        @endif

        @if ($order->isQueue())
            <a href="{{ route('employees.order.appointTeam', ['order' => $order]) }}" class="btn btn-success mr-1">
                {{ __('order.action.appointTeam') }}
            </a>
        @endif

        @if ($order->isExecute())
            <a href="{{ route('employees.order.reassignTeam', ['order' => $order]) }}" class="btn btn-success mr-1">
                {{ __('order.action.reassignTeam') }}
            </a>
        @endif

        @can('manage-team-fine', $order)
            <a href="{{ route('employees.order.createFine', ['order' => $order]) }}" class="btn btn-danger">
                {{ __('teamFine.action.create') }}
            </a>
        @endcan

        @if($order->hasTeamFine() && $order->getBaseTeamFine()->isActive())
            <a class="btn btn-danger mr-1" href="{{ route('employees.order.disableFine', $order->getBaseTeamFine()) }}">
                {{ __('teamFine.action.disable') }}
            </a>
        @endif

        @can('manage-cross-order', $order)
            <a class="btn btn-danger mr-1" href="{{ route('employees.order.cross', $order) }}">
                {{ __('order.action.crossItOut') }}
            </a>
        @endcan
    </div>

    @if($order->hasDiscountCard() && !$order->discountCard->hasNumber())
        @include('partials.flash._template', ['type' => 'warning', 'message' => __('discountCard.message.notExistNumber') ])
    @endif

    <div class="card">
        <div class="card-body">
            <div>
                <p><strong>{{ __('order.field.id') }}: </strong>{{ $order->id }}</p>
                <p>
                    <strong>
                        {{ __('order.field.status') }}:
                    </strong>
                    @include('employees.order.partials._status', ['order' => $order])
                </p>
                <p><strong>{{ __('order.field.teamName') }}: </strong>{{ $order->team_name }}</p>
                <p><strong>{{ __('order.field.key') }}: </strong>{{ $order->number_key }}</p>
                <p>
                    <strong>
                        {{ __('order.field.number') }}:
                    </strong>
                    {{ $order->car->number }}
                    {{ $order->car->carMark->name }}
                    {{ $order->car->carModel->name }}
                </p>
                <p><strong>{{ __('order.field.phone') }}: </strong>{{ phoneFormat($order->client->phone) }}</p>
                <p><strong>{{ __('order.field.date') }}: </strong>{{ dataTimeFormat($order->created_at) }}</p>
                <p>
                    <strong>{{ __('order.field.works') }}: </strong>
                    @foreach($order->basketItems as $item)
                        {{ $item->work->number }}{{ $loop->last ? '' : ',' }}
                    @endforeach
                </p>
                @include('employees.order.partials._orderPrice', ['order' => $order])
                @if (isset($order->admin_comment))
                    <p>
                        <strong>{{ __('order.field.adminComment') }}:</strong><br>
                        {!! nl2br(e($order->admin_comment)) !!}
                    </p>
                @endif
                @if (isset($order->comment))
                    <p>
                        <strong>{{ __('order.field.cashierComment') }}:</strong><br>
                        {!! nl2br(e($order->comment)) !!}
                    </p>
                @endif
            </div>
        </div>
    </div>

    @if (! $order->isCompleted())
        <div class="card mt-3">
            <div class="card-header">
                {{ __('order.field.comment') }}
            </div>
            <div class="card-body">
                <form method="POST" action="{{ route('employees.order.adminComment', [$order]) }}">
                    @csrf
                    @method("PATCH")

                    <div class="form-group row">
                        <label for="comment" class="col-md-4 col-form-label text-md-right">
                            {{ __('order.field.comment') }}
                        </label>

                        <div class="col-md-6">
                            <textarea required autocomplete="off" id="comment" class="comment-input form-control{{ $errors->has('comment') ? ' is-invalid' : '' }}" name="comment">{{ old('comment', $order->admin_comment) }}</textarea>

                            @if ($errors->has('comment'))
                                <span class="invalid-feedback">
                                    <strong>{{ $errors->first('comment') }}</strong>
                                </span>
                            @endif
                        </div>
                    </div>

                    <div class="form-group row mb-0">
                        <div class="col-md-6 offset-md-4">
                            <button class="btn btn-success">
                                {{ __('order.action.comment') }}
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    @endif

    <div class="card mt-3">
        <div class="card-header">
            {{ __('team.block') }}
        </div>
        <div class="card-body">
            <div>
                <p><strong>{{ __('team.field.name') }}: </strong>{{ $order->team_name }}</p>
                <p><strong>{{ __('team.field.admin') }}: </strong>{{ $order->admin->getFio()->getFullName() }}</p>
                @if ($order->employees->count())
                    <p>
                        <strong>{{ __('team.field.employees') }}: </strong>
                        {{ listEmployees($order->employees) }}
                    </p>
                @endif
            </div>
        </div>
    </div>

    @if ($order->hasTeamFine())
        <div class="card mt-3">
            <div class="card-header">
                {{ __('teamFine.block') }}
            </div>
            <div class="card-body pb-0">
                <div>
                    <p>
                        <strong>{{ __('teamFine.field.status') }}: </strong>
                        @include('employees.fine._status', ['fine' => $order->getBaseTeamFine()])
                    </p>
                    <p>
                        <strong>{{ __('teamFine.field.value') }}: </strong>
                        <span class="rub">
                            {{ moneyFormat($order->getBaseTeamFine()->value) }}
                        </span>
                    </p>
                </div>
            </div>

            <div class="list">
                @forelse($order->getBaseTeamFine()->histories as $history)
                    <div class="list__item">
                        <p class="list__attribute attribute">
                            <span class="attribute__name">{{ __('personalFine.field.sum') }}:</span>
                            <span class="attribute__value rub">
                                {{ moneyFormat($history->value) }}
                            </span>
                        </p>
                        <p class="list__attribute attribute">
                            <span class="attribute__name">{{ __('personalFine.field.date') }}:</span>
                            <span class="attribute__value">
                                {{ dataTimeFormat($history->timestamp) }}
                            </span>
                        </p>
                        <p class="list__attribute attribute">
                            <span class="attribute__name">{{ __('personalFine.field.comment') }}:</span>
                            <span class="attribute__value">
                                {!! nl2br(e($history->comment)) !!}
                            </span>
                        </p>
                    </div>
                @empty
                    <div class="p-3">
                        {{ __('teamFine.historyBlock.notFound') }}
                    </div>
                @endforelse
            </div>
        </div>
    @endif
@endsection