routes/web.php
<?php



Route::get('/', function () {
    dd(1);
});

Route::get('/', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('/', 'Auth\LoginController@login');
Route::post('/logout', 'Auth\LoginController@logout')->name('logout');

Route::group(
    [
        'prefix' => 'employees',
        'as' => 'employees.',
        'namespace' => 'Employees',
        'middleware' => ['auth', 'mustByActive'],
    ],
    function () {
        Route::get('/contract/autocomplete', 'ContractController@autocomplete')->name('contract.autocomplete');
        Route::get('/client/autocomplete', 'ClientController@autocomplete')->name('client.autocomplete');
        Route::get('/car/autocomplete', 'CarController@autocomplete')->name('car.autocomplete');
        Route::get('/car-model', 'CarModelController@byMark')->name('carModel.byMark');

        Route::group(
            [
                'prefix' => 'discount-card',
                'as' => 'discountCard.',
            ],
            function () {
                Route::get('', 'DiscountCardController@list')->name('list');
                Route::get('/create', 'DiscountCardController@createForm')->name('create');
                Route::post('/create', 'DiscountCardController@create');
                Route::get('/check', 'DiscountCardController@check')->name('check');

                Route::get('/{discountCard}/edit', 'DiscountCardController@editForm')->name('edit');
                Route::put('/{discountCard}/edit', 'DiscountCardController@edit');
                Route::get('/{discountCard}/edit-disc', 'DiscountCardController@editDiscForm')->name('editDisc');
                Route::put('/{discountCard}/edit-disc', 'DiscountCardController@editDisc');

                Route::get('/{discountCard}', 'DiscountCardController@show')->name('show');
            }
        );

        Route::group(
            [
                'prefix' => 'cafe',
                'as' => 'cafe.'
            ],
            function () {
                Route::get('/sale', 'CafeController@createSaleForm')->name('createSale');
                Route::post('/sale', 'CafeController@createSale');
            }
        );

        Route::group(
            [
                'prefix' => 'order',
                'as' => 'order.',
                'namespace' => 'Order',
            ],
            function () {
                Route::get('', 'OrderController@list')->name('list');

                Route::get('/service-history', 'ServiceHistoryController@list')->name('serviceHistory');

                Route::get('/check-new-order', 'PaymentController@checkNewOrder')->name('checkNewOrder');
                Route::get('/user-register', 'ClientRegisterController@registerForm')->name('clientRegister');
                Route::post('/user-register', 'ClientRegisterController@register');

                Route::get('/{car}/{client}/ordering', 'OrderingController@orderingForm')->name('ordering');
                Route::post('/{car}/{client}/ordering', 'OrderingController@ordering');

                Route::get('/{order}', 'OrderingController@show')->name('show');

                Route::get('/{order}/edit-works', 'OrderingController@editWorksForm')->name('editWorks');
                Route::patch('/{order}/edit-works', 'OrderingController@editWorks');

                Route::patch('/{order}/admin-comment', 'OrderingController@comment')->name('adminComment');

                Route::get('/list/payment', 'PaymentController@list')->name('payment.list');
                Route::get('/{order}/payment', 'PaymentController@paymentForm')->name('payment');
                Route::post('/{order}/payment', 'PaymentController@payment');
                Route::put('/{order}/repayment', 'PaymentController@repayment')->name('repayment');
                Route::post('/{order}/payment-refusal', 'PaymentController@refusal')->name('paymentRefusal');

                Route::get('/list/overdrive', 'OverdriveController@list')->name('overdrive.list');
                Route::get('/{order}/appoint-team', 'AppointTeamController@appointTeamForm')->name('appointTeam');
                Route::patch('/{order}/appoint-team', 'AppointTeamController@appointTeam');

                Route::get('/{order}/reassign-team', 'AppointTeamController@reassignTeamForm')->name('reassignTeam');
                Route::patch('/{order}/reassign-team', 'AppointTeamController@reassignTeam');

                Route::patch('/{order}/comment', 'PaymentController@comment')->name('comment');

                Route::get('/{order}/fine', 'FineController@createForm')->name('createFine');
                Route::post('/{order}/fine', 'FineController@create');

                Route::get('/{order}/cross', 'FineController@crossForm')->name('cross');
                Route::post('/{order}/cross', 'FineController@cross');

                Route::patch('/{order}/executed', 'OrderingController@executed')->name('executed');

                Route::get('/fine/{fine}/disable', 'FineController@disableForm')->name('disableFine');
                Route::put('/fine/{fine}/disable', 'FineController@disable');
            }
        );

        Route::group(
            [
                'prefix' => 'teams',
                'as' => 'teams.',
            ],
            function () {
                Route::get('', 'TeamController@list')->name('list');
                Route::get('/create', 'TeamController@createForm')->name('create');
                Route::post('/create', 'TeamController@create');
                Route::get('/{team}', 'TeamController@show')->name('show');
                Route::get('/{team}/edit', 'TeamController@editForm')->name('edit');
                Route::put('/{team}/edit', 'TeamController@edit');
                Route::delete('/{team}/delete', 'TeamController@delete')->name('delete');
            }
        );

        Route::group(
            [
                'prefix' => 'balance',
                'as' => 'balance.',
            ],
            function () {
                Route::get('', 'BalanceController@common')->name('common');
            }
        );

        Route::group(
            [
                'prefix' => 'accrual',
                'as' => 'accrual.',
                'namespace' => 'Accrual',
            ],
            function () {
                Route::get('', 'AccrualController@common')->name('common');
                Route::get('personal-fine', 'PersonalFineController@list')->name('personalFines');
                Route::get('team-fine', 'TeamFineController@list')->name('teamFines');
                Route::get('employees', 'EmployeesController@list')->name('employees');
            }
        );

        Route::group(
            [
                'prefix' => 'washer',
                'as' => 'washer.',
                'namespace' => 'Washer',
            ],
            function () {
                Route::get('', 'WasherController@list')->name('list');
                Route::get('/{user}', 'WasherController@show')->name('show');

                Route::get('/{user}/fine', 'PersonalFineController@createForm')->name('createFine');
                Route::post('/{user}/fine', 'PersonalFineController@create');

                Route::get('/personal-fine/{fine}', 'PersonalFineController@show')->name('showPersonalFine');
                Route::get('/personal-fine/{fine}/disable', 'PersonalFineController@disableForm')->name('disablePersonalFine');
                Route::put('/personal-fine/{fine}/disable', 'PersonalFineController@disable');
                Route::get('/{user}/personal-fines', 'PersonalFineController@list')->name('personalFines');
                Route::get('/{user}/team-fines', 'TeamFineController@list')->name('teamFines');
                Route::get('/{user}/salary-breakdown', 'SalaryBreakdownController@index')->name('salaryBreakdown');
            }
        );
    }
);

Route::group(
    [
        'prefix' => 'super_admin',
        'as' => 'superAdmin.',
        'namespace' => 'SuperAdmin',
        'middleware' => ['auth', 'mustByActive', App\Http\Middleware\SuperAdmin::class],
    ],
    function () {
        Route::get('/', 'HomeController@index')->name('home');

        Route::group(
            [
                'prefix' => 'fine',
                'as' => 'fine.',
                'namespace' => 'Fine',
            ],
            function () {
                Route::get('payment-refusal-fine-size', 'PaymentRefusalFineSizeController@form')->name('paymentRefusalFineSize');
                Route::put('payment-refusal-fine-size', 'PaymentRefusalFineSizeController@change');
            }
        );

        Route::group(
            [
                'prefix' => 'service_center',
                'as' => 'serviceCenter.'
            ],
            function () {
                Route::get('', 'ServiceCentersController@list')->name('list');
                Route::get('/create', 'ServiceCentersController@createForm')->name('create');
                Route::post('/create', 'ServiceCentersController@create');
                Route::get('/{serviceCenter}', 'ServiceCentersController@show')->name('show');
                Route::get('/{serviceCenter}/edit', 'ServiceCentersController@editForm')->name('edit');
                Route::put('/{serviceCenter}/edit', 'ServiceCentersController@edit');
                Route::delete('/{serviceCenter}/delete', 'ServiceCentersController@delete')->name('delete');
            }
        );

        Route::group(
            [
                'prefix' => 'car_wash',
                'as' => 'carWash.',
                'namespace' => 'CarWash',
            ],
            function () {
                Route::group(
                    [
                        'prefix' => 'works',
                        'as' => 'works.',
                    ],
                    function () {
                        Route::get('', 'WorksController@index')->name('list');

app/Http/Controllers/Employees/Order/AppointTeamController.php
<?php

namespace App\Http\Controllers\Employees\Order;

use App\Entity\CarModel;
use App\Entity\Client;
use App\Entity\Order\Order;
use App\Entity\Team;
use App\Entity\User\Role;
use App\Entity\User\User;
use App\Http\Controllers\Controller;
use App\Http\Requests\Order\AppointTeamRequest;
use App\Services\Exception\NotFoundEmployees;
use App\Services\OrderService;
use App\Services\TeamService;
use App\Services\ViewOrder\ViewOrder;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class AppointTeamController extends Controller
{
    private $service;
    private $teamService;

    public function __construct(OrderService $service, TeamService $teamService)
    {
        $this->middleware(['auth', 'can:manage-overdrive-order']);

        $this->service = $service;
        $this->teamService = $teamService;
    }

    public function appointTeamForm(Order $order)
    {
        if (!$order->isQueue()) {
            return back()
                ->with('error', trans('order.message.appointTeam'));
        }

        /** @var User $user */
        $user = Auth::user();
        $pageTitle = trans('order.page.appointTeam.header');

        $teams = Team::fullTeam($user->serviceCenter);
        $employees = $this->teamService->getEmployees($user);

        $viewOrder = new ViewOrder($order);

        return view('employees.order.appointTeam', compact('pageTitle', 'teams', 'employees', 'viewOrder'));

    }

    public function appointTeam(Order $order, AppointTeamRequest $request)
    {
        if (!$order->isQueue()) {
            return back()
                ->with('error', trans('order.message.appointTeam'));
        }

        /** @var User $user */
        $user = Auth::user();

        $teamId = $request->get('team');
        $employeeIds = $request->get('employees');

        if (! empty($employeeIds)) {
            $teamId = $this->teamService->createForce(trans('team.defaultName', ['num' => $order->car->number]), $employeeIds, $user->serviceCenter)->id;
        }

        if (is_null($teamId)) {
            $this->fieldValidationError($request, ['team' => trans('order.message.needSelectTeamOrEmployees')]);
        }

        try {
            $this->service->appointTeam($order, $teamId, $user);
        } catch (NotFoundEmployees $err) {
            $this->fieldValidationError($request, ['team' => trans('order.message.notFoundEmployees')]);
        }

        return redirect()
            ->to($user->isOverdrive() ? route('employees.order.overdrive.list') : route('employees.order.list'))
            ->with('success', trans('order.message.successAppointTeam'));
    }

    public function reassignTeamForm(Order $order)
    {

        if (!$order->isExecute()) {
            return back()
                ->with('error', trans('order.message.reassignTeam'));
        }

        /** @var User $user */
        $user = Auth::user();
        $pageTitle = trans('order.page.reassignTeam.header');

        $teams = Team::fullTeam($user->serviceCenter);
        $employees = $this->teamService->getEmployees($user);

        $viewOrder = new ViewOrder($order);
        $viewOrder->employeeIdsToNull();

        return view('employees.order.reassignTeam', compact('pageTitle', 'teams', 'employees', 'viewOrder'));
    }

    public function reassignTeam(Order $order, AppointTeamRequest $request)
    {
        if (!$order->isExecute()) {
            return back()
                ->with('error', trans('order.message.reassignTeam'));
        }

        /** @var User $user */
        $user = Auth::user();

        $teamId = $request->get('team');
        $employeeIds = $request->get('employees');

        $this->teamService->deleteEmployeesTemporaryTeam($order->employees);

        if (! empty($employeeIds)) {
            $teamId = $this->teamService->createForce(trans('team.defaultName', ['num' => $order->car->number]), $employeeIds, $user->serviceCenter)->id;
        }

        if (is_null($teamId)) {
            $this->fieldValidationError($request, ['team' => trans('order.message.needSelectTeamOrEmployees')]);
        }

        try {
            $this->service->reassignTeam($order, $teamId, $user);
        } catch (NotFoundEmployees $err) {
            $this->fieldValidationError($request, ['team' => trans('order.message.notFoundEmployees')]);
        }

        return redirect()
            ->to($user->isOverdrive() ? route('employees.order.overdrive.list') : route('employees.order.list'))
            ->with('success', trans('order.message.successAppointTeam'));
    }
}

app/Http/Controllers/Employees/Order/FineController.php
<?php

namespace App\Http\Controllers\Employees\Order;

use App\Entity\User\Fine\TeamFine;
use App\Entity\Order\Order;
use App\Entity\User\User;
use App\Http\Controllers\Controller;
use App\Http\Requests\Order\CreateFineRequest;
use App\Http\Requests\Order\CrossRequest;
use App\Http\Requests\Order\DisableFineRequest;
use App\Services\TeamFineService;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Gate;

class FineController extends Controller
{
    private $service;

    public function __construct(TeamFineService $service)
    {
        $this->middleware(['auth']);
        $this->service = $service;
    }

    public function createForm(Order $order)
    {
        Gate::denies('manage-team-fine', $order) and abort(403);

        $pageTitle = trans('teamFine.page.create.header');
        $teamFine = new TeamFine();
        return view('employees.order.fine', compact('pageTitle', 'teamFine'));
    }

    public function create(Order $order, CreateFineRequest $request)
    {
        Gate::denies('manage-team-fine', $order) and abort(403);

        /** @var User $creator */
        $creator = Auth::user();

        $this->service->create($order, $creator, $request);

        return redirect()
            ->to(route('employees.order.show', $order))
            ->with('success', trans('teamFine.message.successFine'));
    }

    public function disableForm(TeamFine $fine)
    {
        Gate::denies('manage-disable-team-fine', $fine->order) and abort(403);
        if(! $fine->isActive()) {
            abort(400);
        }

        $pageTitle = trans('teamFine.page.disable.header');
        $fine = new TeamFine();
        return view('employees.fine.team.disable', compact('pageTitle', 'fine'));
    }

    public function disable(DisableFineRequest $request, TeamFine $fine)
    {
        Gate::denies('manage-disable-team-fine', $fine->order) and abort(403);
        if(! $fine->isActive()) {
            abort(400);
        }

        /** @var User $user */
        $user = Auth::user();
        $this->service->disable($fine, $user, $request);

        return redirect()
            ->to(route('employees.order.show', $fine->order))
            ->with('success', trans('teamFine.message.successDisabledFine'));
    }

    public function crossForm(Order $order)
    {
        Gate::denies('manage-cross-order', $order) and abort(403);

        $pageTitle = trans('order.page.cross.header');
        $fine = new TeamFine();
        return view('employees.order.cross', compact('pageTitle', 'fine'));
    }

    public function cross(CrossRequest $request, Order $order)
    {
        Gate::denies('manage-cross-order', $order) and abort(403);

        /** @var User $user */
        $user = Auth::user();
        $this->service->cross($order, $user, $request);

        return redirect()
            ->to(route('employees.order.show', $order))
            ->with('success', trans('order.message.successCross'));
    }

}

resources/views/employees/order/partials/_markAndModel.blade.php
<div class="mark-and-model">
    <div class="mark-and-model__mark car-mark form-group row {{ (old('mark', '') != '' || isset($car) || isset($showModel)) ? '' : 'hidden' }}">
        <label for="mark" class="col-md-4 col-form-label text-md-right">
            {{ __('order.field.mark') }}@if (!isset($notRequired) || !$notRequired)<sup class="text-danger">*</sup>@endif
        </label>

        <div class="car-mark__select col-md-6 {{ old('new-mark', null) === null ? '' : 'hidden' }}">
            <select
                    autocomplete="off"
                    id="mark"
                    data-location_car_model="{{ route('employees.carModel.byMark') }}"
                    @if (!isset($notRequired) || !$notRequired)
                        required
                    @endif
                    class="form-control{{ $errors->has('mark') ? ' is-invalid' : '' }}"
                    name="mark"
            >
                <option></option>
                @foreach ($carMarks as $carMark)
                    <option value="{{ $carMark->id }}" {{ $carMark->id == old('mark', isset($car) ? $car->carMark->id : '') ? ' selected' : '' }}>{{ $carMark->name }}</option>
                @endforeach
                <option value="0" {{ '0' === old('mark', isset($car) ? $car->carMark->id : '') ? ' selected' : '' }}>{{ __('order.anotherMark') }}</option>
                <option value="-1" {{ '-1' === old('mark', isset($car) ? $car->carMark->id : '') ? ' selected' : '' }}>{{ __('order.createMark') }}</option>
            </select>

            @if ($errors->has('mark'))
                <span class="invalid-feedback">
                    <strong>{{ $errors->first('mark') }}</strong>
                </span>
            @endif
        </div>

        <div class="car-mark__input col-md-6 {{ old('new-mark', null) === null ? 'hidden' : '' }}">
            <input id="new-mark" type="text" class="form-control{{ $errors->has('new-mark') ? ' is-invalid' : '' }}" name="new-mark" value="{{ old('new-mark', '') }}">

            @if ($errors->has('new-mark'))
                <span class="invalid-feedback">
                    <strong>{{ $errors->first('new-mark') }}</strong>
                </span>
            @endif
        </div>
    </div>

    <div class="car-model form-group row {{ (old('mark', '') != '' || isset($car) || isset($showModel)) ? '' : 'hidden' }}">
        <label for="model" class="col-md-4 col-form-label text-md-right">
            {{ __('order.field.model') }}@if (!isset($notRequired) || !$notRequired)<sup class="text-danger">*</sup>@endif
        </label>

        <div class="col-md-6 car-model__input {{ old('new-mark', null) === null && old('new-model', null) === null ? 'hidden' : '' }}">
            <input id="new-model" type="text" class="form-control{{ $errors->has('new-model') ? ' is-invalid' : '' }}" name="new-model" value="{{ old('new-model', '') }}">
        </div>

        <div class="col-md-6 car-model__select">
            <select
                    autocomplete="off"
                    id="model"
                    @if (!isset($notRequired) || !$notRequired)
                        required
                    @endif
                    class="form-control{{ $errors->has('model') ? ' is-invalid' : '' }}"
                    name="model"
            >
                @foreach ($carModels as $carModel)
                    <option value="{{ $carModel->id }}" {{ $carModel->id == old('model', isset($car) ? $car->carModel->id : '') ? ' selected' : '' }}>
                        {{ $carModel->name }}
                    </option>
                @endforeach
            </select>

            <script type="text/template" class="model__items-template">
                <% items.forEach(function(item) { %>
                    <option value="<%-item.id%>" <%= modelId === item.id ? 'selected' : '' %>>
                        <%-item.name%>
                        <% if(item.category !== undefined) {%>
                            - <%-item.category.name%>
                       <% } %>
                    </option>
                <% }); %>
            </script>

            @if ($errors->has('model'))
                <span class="invalid-feedback">
                    <strong>{{ $errors->first('model') }}</strong>
                </span>
            @endif
        </div>
    </div>
</div>

resources/views/employees/order/partials/_nav.blade.php
<ul class="nav nav-tabs mb-3">
    @can ('manage-order')
        @foreach($statuses as $status)
            <li class="nav-item order-filter-status" data-value="{{ isset($status['value']) ? $status['value'] : -1 }}">
                <a
                        class="
                            nav-link
                            {{
                                (
                                    Route::currentRouteNamed('employees.order.list')
                                    && (
                                        ($currentStatus == -1 && !isset($status['value']))
                                        || ($currentStatus == $status['value'] && isset($status['value']) && $currentStatus !== null)
                                    )
                                ) ? 'active' : ''
                            }}"
                        href="#"
                >
                    {{ $status['label'] }}
                </a>
            </li>
        @endforeach
    @endcan
</ul>

resources/views/employees/order/partials/_orderPrice.blade.php
@if ($order->hasContract())
    <div class="cost mb-2">
        <div class="cost__label">
            <strong>
                {{ __('order.phrase.sumByContract') }}
            </strong>
            ({{ __('order.phrase.discount', ['disc' => $order->getDisc()]) }})<strong>:</strong>
        </div>
        <div class="cost__value">{{ moneyFormat($order->price()) }}</div>
    </div>
@elseif ($order->isApplyingDiscountFromContract())
    <div class="cost mb-2">
        <div class="cost__label">
            <strong>
                {{ __('order.phrase.sumWithDisc') }}
            </strong>
            ({{ __('order.phrase.discountFromContract', ['disc' => $order->getDisc()]) }})<strong>:</strong>
        </div>
        <div class="cost__value">{{ moneyFormat($order->price()) }}</div>
    </div>
@elseif ($order->hasDiscountCard())
    <div class="cost mb-2">
        <div class="cost__label">
            <strong>
                {{ __('order.phrase.sumWithDisc') }}
            </strong>
            ({{ __('discountCard.title.defined', ['disc' => $order->getDisc()]) }})<strong>:</strong>
        </div>
        <div class="cost__value">{{ moneyFormat($order->price()) }}</div>
    </div>
@else
    <div class="cost mb-2">
        <div class="cost__label">{{ __('order.phrase.sum') }}:</div>
        <div class="cost__value">{{ moneyFormat($order->price()) }}</div>
    </div>
@endif

@if ($order->isCompleted() && $order->isOtherPaymentPrice())
    <div class="cost mb-2">
        <div class="cost__label">{{ __('order.phrase.paymentSum') }}:</div>
        <div class="cost__value">{{ moneyFormat($order->paymentPrice()) }}</div>
    </div>
@endif

resources/views/employees/order/partials/_status.blade.php
@if ($order->isExecute())
    <span class="badge badge-danger">{{ __('order.status.execute') }}</span>
@elseif ($order->isExecuted())
    <span class="badge badge-info">{{ __('order.status.executed') }}</span>
@elseif ($order->isPaid())
    <span class="badge badge-success">{{ __('order.status.paid') }}</span>
@elseif ($order->isQueue())
    <span class="badge badge-warning">{{ __('order.status.queue') }}</span>
@elseif ($order->isPaymentRefusal())
    <span class="badge badge-dark">{{ __('order.status.paymentRefusal') }}</span>
@elseif ($order->isCanceled())
    <span class="badge badge-secondary">{{ __('order.status.canceled') }}</span>
@endif

@if (!(isset($notShowCross) && $notShowCross))
    @if ($order->hasCrossTeamFine())
        <span class="badge badge-danger">{{ __('order.status.cross') }}</span>
    @endif
@endif

resources/views/employees/order/partials/_team.blade.php
<div class="form-group row">
    <label for="team" class="col-md-4 col-form-label text-md-right">
        {{ __('order.selectTeam') }}<sup class="text-danger">*</sup>
    </label>

    <div class="col-md-6">

        <select autocomplete="off" id="team" class="form-control{{ $errors->has('team') ? ' is-invalid' : '' }}" name="team">
            @foreach ($teams as $team)
                <option
                        value="{{ $team->id }}"
                        {{ $team->id == old('team', $viewOrder->getTeam()) ? ' selected' : '' }}
                        class="option-space"
                >
                    {{ $team->name }}
                </option>
            @endforeach

            @if($create)
                <option
                        value="0"
                        {{ 0 == old('team', $viewOrder->getTeam()) ? ' selected' : '' }}
                        class="option-space"
                >
                    {{ __('team.withoutTeam') }}
                </option>
            @endif
        </select>

        @if ($errors->has('team'))
            <span class="invalid-feedback">
                <strong>{{ $errors->first('team') }}</strong>
            </span>
        @endif
    </div>
</div>

<div class="form-group row">
    <label for="employees" class="col-md-4 col-form-label text-md-right">
        {{ __('order.createTeam') }}
    </label>

    <div class="col-md-6 mb-2">
        <button type="button" class="btn btn-light" data-toggle="collapse" data-target="#employees">{{ __('team.showEmployees') }}</button>
    </div>

    <div id="employees" class="collapse col-12">
        <div class="row">
            <div class="col-md-4"></div>
            @include('employees.teams._employees', ['employees' => $employees, 'employeesIds' => $viewOrder->getEmployees()])
        </div>
    </div>

</div>