routes/web.php
<?php



Route::get('/', function () {
    dd(1);
});

Route::get('/', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('/', 'Auth\LoginController@login');
Route::post('/logout', 'Auth\LoginController@logout')->name('logout');

Route::group(
    [
        'prefix' => 'employees',
        'as' => 'employees.',
        'namespace' => 'Employees',
        'middleware' => ['auth', 'mustByActive'],
    ],
    function () {
        Route::get('/contract/autocomplete', 'ContractController@autocomplete')->name('contract.autocomplete');
        Route::get('/client/autocomplete', 'ClientController@autocomplete')->name('client.autocomplete');
        Route::get('/car/autocomplete', 'CarController@autocomplete')->name('car.autocomplete');
        Route::get('/car-model', 'CarModelController@byMark')->name('carModel.byMark');

        Route::group(
            [
                'prefix' => 'discount-card',
                'as' => 'discountCard.',
            ],
            function () {
                Route::get('', 'DiscountCardController@list')->name('list');
                Route::get('/create', 'DiscountCardController@createForm')->name('create');
                Route::post('/create', 'DiscountCardController@create');
                Route::get('/check', 'DiscountCardController@check')->name('check');

                Route::get('/{discountCard}/edit', 'DiscountCardController@editForm')->name('edit');
                Route::put('/{discountCard}/edit', 'DiscountCardController@edit');
                Route::get('/{discountCard}/edit-disc', 'DiscountCardController@editDiscForm')->name('editDisc');
                Route::put('/{discountCard}/edit-disc', 'DiscountCardController@editDisc');

                Route::get('/{discountCard}', 'DiscountCardController@show')->name('show');
            }
        );

        Route::group(
            [
                'prefix' => 'cafe',
                'as' => 'cafe.'
            ],
            function () {
                Route::get('/sale', 'CafeController@createSaleForm')->name('createSale');
                Route::post('/sale', 'CafeController@createSale');
            }
        );

        Route::group(
            [
                'prefix' => 'order',
                'as' => 'order.',
                'namespace' => 'Order',
            ],
            function () {
                Route::get('', 'OrderController@list')->name('list');

                Route::get('/service-history', 'ServiceHistoryController@list')->name('serviceHistory');

                Route::get('/check-new-order', 'PaymentController@checkNewOrder')->name('checkNewOrder');
                Route::get('/user-register', 'ClientRegisterController@registerForm')->name('clientRegister');
                Route::post('/user-register', 'ClientRegisterController@register');

                Route::get('/{car}/{client}/ordering', 'OrderingController@orderingForm')->name('ordering');
                Route::post('/{car}/{client}/ordering', 'OrderingController@ordering');

                Route::get('/{order}', 'OrderingController@show')->name('show');

                Route::get('/{order}/edit-works', 'OrderingController@editWorksForm')->name('editWorks');
                Route::patch('/{order}/edit-works', 'OrderingController@editWorks');

                Route::patch('/{order}/admin-comment', 'OrderingController@comment')->name('adminComment');

                Route::get('/list/payment', 'PaymentController@list')->name('payment.list');
                Route::get('/{order}/payment', 'PaymentController@paymentForm')->name('payment');
                Route::post('/{order}/payment', 'PaymentController@payment');
                Route::put('/{order}/repayment', 'PaymentController@repayment')->name('repayment');
                Route::post('/{order}/payment-refusal', 'PaymentController@refusal')->name('paymentRefusal');

                Route::get('/list/overdrive', 'OverdriveController@list')->name('overdrive.list');
                Route::get('/{order}/appoint-team', 'AppointTeamController@appointTeamForm')->name('appointTeam');
                Route::patch('/{order}/appoint-team', 'AppointTeamController@appointTeam');

                Route::get('/{order}/reassign-team', 'AppointTeamController@reassignTeamForm')->name('reassignTeam');
                Route::patch('/{order}/reassign-team', 'AppointTeamController@reassignTeam');

                Route::patch('/{order}/comment', 'PaymentController@comment')->name('comment');

                Route::get('/{order}/fine', 'FineController@createForm')->name('createFine');
                Route::post('/{order}/fine', 'FineController@create');

                Route::get('/{order}/cross', 'FineController@crossForm')->name('cross');
                Route::post('/{order}/cross', 'FineController@cross');

                Route::patch('/{order}/executed', 'OrderingController@executed')->name('executed');

                Route::get('/fine/{fine}/disable', 'FineController@disableForm')->name('disableFine');
                Route::put('/fine/{fine}/disable', 'FineController@disable');
            }
        );

        Route::group(
            [
                'prefix' => 'teams',
                'as' => 'teams.',
            ],
            function () {
                Route::get('', 'TeamController@list')->name('list');
                Route::get('/create', 'TeamController@createForm')->name('create');
                Route::post('/create', 'TeamController@create');
                Route::get('/{team}', 'TeamController@show')->name('show');
                Route::get('/{team}/edit', 'TeamController@editForm')->name('edit');
                Route::put('/{team}/edit', 'TeamController@edit');
                Route::delete('/{team}/delete', 'TeamController@delete')->name('delete');
            }
        );

        Route::group(
            [
                'prefix' => 'balance',
                'as' => 'balance.',
            ],
            function () {
                Route::get('', 'BalanceController@common')->name('common');
            }
        );

        Route::group(
            [
                'prefix' => 'accrual',
                'as' => 'accrual.',
                'namespace' => 'Accrual',
            ],
            function () {
                Route::get('', 'AccrualController@common')->name('common');
                Route::get('personal-fine', 'PersonalFineController@list')->name('personalFines');
                Route::get('team-fine', 'TeamFineController@list')->name('teamFines');
                Route::get('employees', 'EmployeesController@list')->name('employees');
            }
        );

        Route::group(
            [
                'prefix' => 'washer',
                'as' => 'washer.',
                'namespace' => 'Washer',
            ],
            function () {
                Route::get('', 'WasherController@list')->name('list');
                Route::get('/{user}', 'WasherController@show')->name('show');

                Route::get('/{user}/fine', 'PersonalFineController@createForm')->name('createFine');
                Route::post('/{user}/fine', 'PersonalFineController@create');

                Route::get('/personal-fine/{fine}', 'PersonalFineController@show')->name('showPersonalFine');
                Route::get('/personal-fine/{fine}/disable', 'PersonalFineController@disableForm')->name('disablePersonalFine');
                Route::put('/personal-fine/{fine}/disable', 'PersonalFineController@disable');
                Route::get('/{user}/personal-fines', 'PersonalFineController@list')->name('personalFines');
                Route::get('/{user}/team-fines', 'TeamFineController@list')->name('teamFines');
                Route::get('/{user}/salary-breakdown', 'SalaryBreakdownController@index')->name('salaryBreakdown');
            }
        );
    }
);

Route::group(
    [
        'prefix' => 'super_admin',
        'as' => 'superAdmin.',
        'namespace' => 'SuperAdmin',
        'middleware' => ['auth', 'mustByActive', App\Http\Middleware\SuperAdmin::class],
    ],
    function () {
        Route::get('/', 'HomeController@index')->name('home');

        Route::group(
            [
                'prefix' => 'fine',
                'as' => 'fine.',
                'namespace' => 'Fine',
            ],
            function () {
                Route::get('payment-refusal-fine-size', 'PaymentRefusalFineSizeController@form')->name('paymentRefusalFineSize');
                Route::put('payment-refusal-fine-size', 'PaymentRefusalFineSizeController@change');
            }
        );

        Route::group(
            [
                'prefix' => 'service_center',
                'as' => 'serviceCenter.'
            ],
            function () {
                Route::get('', 'ServiceCentersController@list')->name('list');
                Route::get('/create', 'ServiceCentersController@createForm')->name('create');
                Route::post('/create', 'ServiceCentersController@create');
                Route::get('/{serviceCenter}', 'ServiceCentersController@show')->name('show');
                Route::get('/{serviceCenter}/edit', 'ServiceCentersController@editForm')->name('edit');
                Route::put('/{serviceCenter}/edit', 'ServiceCentersController@edit');
                Route::delete('/{serviceCenter}/delete', 'ServiceCentersController@delete')->name('delete');
            }
        );

        Route::group(
            [
                'prefix' => 'car_wash',
                'as' => 'carWash.',
                'namespace' => 'CarWash',
            ],
            function () {
                Route::group(
                    [
                        'prefix' => 'works',
                        'as' => 'works.',
                    ],
                    function () {
                        Route::get('', 'WorksController@index')->name('list');

app/helpers.php
<?php

use App\Entity\User\User;

if (! function_exists('dataTimeFormat')) {

    function dataTimeFormat(Carbon\Carbon $date)
    {
        return $date->format("d.m.Y H:i:s");
    }
}

if (! function_exists('getCurrentDay')) {

    function getCurrentDay()
    {
        return dateToPickerFormat(Carbon\Carbon::now());
    }
}

if (! function_exists('getCurrentMonth')) {

    function getCurrentMonth()
    {
        return dateToPickerFormat(Carbon\Carbon::now()->startOfMonth());
    }
}

if (! function_exists('phonesFormat')) {
    function phonesFormat(?array $phones, $noBr = false)
    {
        if (empty($phones)) {
            return null;
        }

        $phones = array_map('phoneFormat', $phones);
        $phones = array_map('e', $phones);

        if ($noBr) {
            $phones = array_map(function ($phone) {
                return "<nobr>$phone</nobr>";
            }, $phones);
        }

        return implode(', ', $phones);
    }
}

if (! function_exists('phoneFormat')) {

    function phoneFormat(?string $phone)
    {
        if (is_null($phone)) {
            return $phone;
        }

        return preg_replace('/(\d)(\d{3})(\d{3})(\d{2})(\d{2})/iu', '$1 ($2) $3-$4-$5', $phone);
    }
}

if (! function_exists('numberFormat')) {

    function numberFormat(\App\ObjectValue\MoneyInterface $money): int
    {
        return (int)(string)$money->round();
    }
}

if (! function_exists('moneyFormat')) {

    function moneyFormat(\App\ObjectValue\MoneyInterface $money): string
    {
        return (string)$money->round();
    }
}

if (! function_exists('moneyInputFormat')) {

    function moneyInputFormat(?\App\ObjectValue\MoneyInterface $money): ?string
    {
        if (is_null($money)) {
            return null;
        }

        return (string)$money->round();
    }
}

if (! function_exists('dateToPickerFormat')) {

    function dateToPickerFormat(?Carbon\Carbon $date)
    {
        if (is_null($date)) {
            return '';
        }

        return $date->format("d.m.Y");
    }
}

if (! function_exists('dateToInputFormat')) {

    function dateToInputFormat(?Carbon\Carbon $date)
    {
        if (is_null($date)) {
            return '';
        }

        return $date->format("Y-m-d");
    }
}

if (! function_exists('listEmployees')) {

    function listEmployees($employees, ?string $link = null)
    {
        $fios = [];
        /** @var App\Entity\User\User $employee */
        foreach ($employees as $employee) {
            $name = e(trim($employee->getFio()->getFullName()));
            if (isset($link)) {
                $href = e(route($link, $employee));
                $name = "<a href='$href'>$name</a>";
            }
            $fios[] = $name;
        }

        return implode(', ', $fios);
    }
}

if (! function_exists('fontColorStyle')) {

    function fontColorStyle(float $visible): string
    {
        $rgba = fontColorRgba($visible);
        return "style=\"color: $rgba !important;\"";
    }
}

if (! function_exists('fontColorRgba')) {

    function fontColorRgba(float $visible): string
    {
        $hex = "#ffffff";
        /** @var User $user */
        $user = Auth::user();
        if (isset($user->serviceCenter) && isset($user->serviceCenter->font_color)) {
            $hex = $user->serviceCenter->font_color;
        }

        $r = $hex[1] . $hex[2];
        $g = $hex[3] . $hex[4];
        $b = $hex[5] . $hex[6];

        return "rgba(" . implode(', ', array_merge(
            array_map("hexdec", [$r, $g, $b]),
            [$visible]
        )) . ")";
    }
}

if (! function_exists('backgroundColor')) {

    function backgroundColor(): string
    {
        /** @var User $user */
        $user = Auth::user();
        if (isset($user->serviceCenter) && isset($user->serviceCenter->background_color)) {
            return $user->serviceCenter->background_color;
        } else {
            return "#343a40";
        }
    }
}

if (! function_exists('declension')) {
    function declension($digit, $expr, $onlyword) {
        $res = '';
        $digit = '' . $digit;
        $expr_list = explode(' ', $expr);
        $reg = '/[^0-9]+/';
        $i = preg_replace($reg, '', $digit);

        if($onlyword) {
            $digit = '';
        }

        if($i >= 5 && $i <= 20) {
            $res = $digit . ' ' . $expr_list[2];
        } else {
            $i %= 10;
            if($i == 1) {
                $res = $digit . ' ' . $expr_list[0];
            } else if($i >= 2 && $i <= 4) {
                $res = $digit . ' ' . $expr_list[1];
            } else {
                $res = $digit . ' ' . $expr_list[2];
            }
        }

        return trim($res);
    }
}

if (! function_exists('dataUpdate')) {
    function dataUpdate(Carbon\Carbon $date) {
        $time = $date->timestamp;
        $timeNow = time();
        if ($timeNow < $time) {
            $timeNow = $time;
        }

        $diffTime = $timeNow  - $time;

        return dataUpdateFromTime($diffTime);
    }
}

if (! function_exists('dataUpdateFromTime')) {
    function dataUpdateFromTime(int $diffTime) {
        $days = trans('time.days');
        $hours = trans('time.hours');
        $mins = trans('time.mins');

        $day = ~~($diffTime / (24 * 60 * 60));
        $hour = ~~($diffTime / (60 * 60) % 24);
        $min = ~~($diffTime / 60 % 60);

        $dateStr = [];

        if (!($day || $hour || $min)) {
            $min = 1;
        }

        if ($day) {
            $dateStr[] = declension($day, $days, false) . ' ';
        }

        if ($hour) {
            $dateStr[] = declension($hour, $hours, false) . ' ';
        }

        if ($min) {
            $dateStr[] = declension($min, $mins, false) . ' ';
        }

        return implode(' ', $dateStr);
    }
}

if (! function_exists('timePassed')) {
    function timePassed(?int $second): string
    {
        if (! isset($second)) {
            return '';
        }

        return dataUpdateFromTime($second);
    }
}

if (! function_exists('orderPaymentType')) {
    function orderPaymentType($type): string
    {
        $map = [
            \App\Entity\Order\Order::PAYMENT_CASH => trans('order.paymentType.cash'),
            \App\Entity\Order\Order::PAYMENT_CARD => trans('order.paymentType.card'),
            \App\Entity\Order\Order::PAYMENT_CONTRACT => trans('order.paymentType.contract'),
        ];

        $title = @$map[$type] ?: '';
        //$title = mb_strtolower($title);

        return $title;
    }
}

app/Http/Controllers/Employees/Accrual/AccrualController.php
<?php

namespace App\Http\Controllers\Employees\Accrual;

use App\Entity\ServiceCenter;
use App\Entity\User\Role;
use App\Entity\User\User;
use App\Http\Controllers\Controller;
use App\Services\AccrualService;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class AccrualController extends Controller
{
    public function __construct()
    {
        $this->middleware(['auth', 'can:manage-accrual']);
    }

    public function common()
    {
        $pageTitle = trans('accrual.page.common.header');
        $commonAccrual = $this->getService()->common();

        return view('employees.accrual.common', compact('pageTitle', 'commonAccrual'));
    }

    private function getService(): AccrualService
    {
        /** @var User $user */
        $user = Auth::user();
        /** @var ServiceCenter $serviceCenter */
        $serviceCenter = $user->serviceCenter;
        return new AccrualService($serviceCenter);
    }
}

resources/views/employees/accrual/_nav.blade.php
<ul class="nav nav-tabs mb-3">
    @can ('manage-accrual')
        <li class="nav-item">
            <a class="nav-link {{ Route::currentRouteNamed('employees.accrual.common') ? 'active' : '' }}" href="{{ route('employees.accrual.common') }}">
                {{ __('navbar.employees.accrual.common') }}
            </a>
        </li>
    @endcan
    @can ('manage-team-fines')
        <li class="nav-item">
            <a class="nav-link {{ Route::currentRouteNamed('employees.accrual.personalFines') ? 'active' : '' }}" href="{{ route('employees.accrual.personalFines') }}">
                {{ __('navbar.employees.accrual.personalFine') }}
            </a>
        </li>
    @endcan
    @can ('manage-personal-fines')
        <li class="nav-item">
            <a class="nav-link {{ Route::currentRouteNamed('employees.accrual.teamFines') ? 'active' : '' }}" href="{{ route('employees.accrual.teamFines') }}">
                {{ __('navbar.employees.accrual.teamFine') }}
            </a>
        </li>
    @endcan
    @can ('manage-accrual')
        <li class="nav-item">
            <a class="nav-link {{ Route::currentRouteNamed('employees.accrual.employees') ? 'active' : '' }}" href="{{ route('employees.accrual.employees') }}">
                {{ __('navbar.employees.accrual.employees') }}
            </a>
        </li>
    @endcan
</ul>

resources/views/employees/accrual/common.blade.php
@extends('employees.layouts.admin')


@section('content')
    @include('employees.accrual._nav')

    <div class="card">
        <div class="list">
            <div class="list__item">
                <p class="list__header">
                    {{ __('accrual.field.today') }}
                </p>
                <p class="list__attribute attribute">
                    <span class="attribute__name">
                        {{ __('accrual.field.orderCount') }}:
                    </span>
                    <span class="attribute__value">
                        {{ $commonAccrual->today->getOrderCount() }}
                    </span>
                </p>
                <p class="list__attribute attribute">
                    <span class="attribute__name">
                        {{ __('accrual.field.receipt') }}:
                    </span>
                    <span class="attribute__value rub">
                        {{ moneyFormat($commonAccrual->today->getReceipt()) }}
                    </span>
                </p>
                <p class="list__attribute attribute">
                    <span class="attribute__name">
                        {{ __('accrual.field.salary') }}:
                    </span>
                    <span class="attribute__value rub">
                        {{ moneyFormat($commonAccrual->today->getSalary()) }}
                    </span>
                </p>
                <p class="list__attribute attribute">
                    <span class="attribute__name">
                        {{ __('accrual.field.fine') }}:
                    </span>
                    <span class="attribute__value rub">
                        {{ moneyFormat($commonAccrual->today->getFine()) }}
                    </span>
                </p>
                <p class="list__attribute attribute">
                    <span class="attribute__name">
                        {{ __('accrual.field.result') }}:
                    </span>
                    <span class="attribute__value rub">
                        {{ moneyFormat($commonAccrual->today->getResult()) }}
                    </span>
                </p>
            </div>
            <div class="list__item">
                <p class="list__header">
                    {{ __('accrual.field.currentMonth') }}
                </p>
                <p class="list__attribute attribute">
                    <span class="attribute__name">
                        {{ __('accrual.field.orderCount') }}:
                    </span>
                    <span class="attribute__value">
                        {{ $commonAccrual->currentMonth->getOrderCount() }}
                    </span>
                </p>
                <p class="list__attribute attribute">
                    <span class="attribute__name">
                        {{ __('accrual.field.receipt') }}:
                    </span>
                    <span class="attribute__value rub">
                        {{ moneyFormat($commonAccrual->currentMonth->getReceipt()) }}
                    </span>
                </p>
                <p class="list__attribute attribute">
                    <span class="attribute__name">
                        {{ __('accrual.field.salary') }}:
                    </span>
                    <span class="attribute__value rub">
                        {{ moneyFormat($commonAccrual->currentMonth->getSalary()) }}
                    </span>
                </p>
                <p class="list__attribute attribute">
                    <span class="attribute__name">
                        {{ __('accrual.field.fine') }}:
                    </span>
                    <span class="attribute__value rub">
                        {{ moneyFormat($commonAccrual->currentMonth->getFine()) }}
                    </span>
                </p>
                <p class="list__attribute attribute">
                    <span class="attribute__name">
                        {{ __('accrual.field.result') }}:
                    </span>
                    <span class="attribute__value rub">
                        {{ moneyFormat($commonAccrual->currentMonth->getResult()) }}
                    </span>
                </p>
            </div>
            <div class="list__item">
                <p class="list__header">
                    {{ __('accrual.field.lastMonth') }}
                </p>
                <p class="list__attribute attribute">
                    <span class="attribute__name">
                        {{ __('accrual.field.orderCount') }}:
                    </span>
                    <span class="attribute__value">
                        {{ $commonAccrual->lastMonth->getOrderCount() }}
                    </span>
                </p>
                <p class="list__attribute attribute">
                    <span class="attribute__name">
                        {{ __('accrual.field.receipt') }}:
                    </span>
                    <span class="attribute__value rub">
                        {{ moneyFormat($commonAccrual->lastMonth->getReceipt()) }}
                    </span>
                </p>
                <p class="list__attribute attribute">
                    <span class="attribute__name">
                        {{ __('accrual.field.salary') }}:
                    </span>
                    <span class="attribute__value rub">
                        {{ moneyFormat($commonAccrual->lastMonth->getSalary()) }}
                    </span>
                </p>
                <p class="list__attribute attribute">
                    <span class="attribute__name">
                        {{ __('accrual.field.fine') }}:
                    </span>
                    <span class="attribute__value rub">
                        {{ moneyFormat($commonAccrual->lastMonth->getFine()) }}
                    </span>
                </p>
                <p class="list__attribute attribute">
                    <span class="attribute__name">
                        {{ __('accrual.field.result') }}:
                    </span>
                    <span class="attribute__value rub">
                        {{ moneyFormat($commonAccrual->lastMonth->getResult()) }}
                    </span>
                </p>
            </div>
        </div>
    </div>
@endsection

resources/views/employees/accrual/employees.blade.php
@extends('employees.layouts.admin')


@section('content')
    @include('employees.accrual._nav')

    <div class="filter">
        <div class="filter__header">{{ __('balance.block.group') }}</div>
        <div class="filter__body">
            <form action="?" method="GET">
                <div class="filter__fields">
                    <div class="filter__field col-md-6">
                        <label for="range" class="filter__label">{{ __('balance.field.date') }}</label>
                        <div class="d-flex">
                            <button
                                    class="btn btn-sm btn-primary change-select-data"
                                    data-target="#dataRange"
                                    data-date="{{ getCurrentDay() }} - {{ getCurrentDay() }}"
                            >
                                {{ __('filtrationBlock.currentDay') }}
                            </button>
                            <button
                                    class="ml-1 mr-1 btn btn-sm btn-primary change-select-data"
                                    data-target="#dataRange"
                                    data-date="{{ getCurrentMonth() }} - {{ getCurrentDay() }}"
                            >
                                {{ __('filtrationBlock.currentMonth') }}
                            </button>
                            <input id="dataRange" autocomplete="off" type="text" name="range" data-range="true" value="{{ dateToPickerFormat($dataRange->getFrom()) }} - {{ dateToPickerFormat($dataRange->getTo()) }}" data-multiple-dates-separator=" - " class="datepicker-here filter__value"/>
                        </div>
                    </div>
                    <div class="filter__field">
                        <label class="filter__label filter__label_empty">&nbsp;</label>
                        <button type="submit" class="filter__button">
                            {{ __('balance.action.showStatistic') }}
                        </button>
                    </div>
                </div>
            </form>
        </div>
    </div>

    <div class="card">
        <div class="list">
            @forelse($accrualCollection->getAccruals() as $employeeId => $accrual)
                <div class="list__item">
                    <p class="list__header">
                        @if ($accrual->getEmployee()->isWasher())
                            <a href="{{ route('employees.washer.show', $employeeId) }}">
                                {{ $accrual->getName() }}
                            </a>
                        @else
                            {{ $accrual->getName() }}
                        @endif
                    </p>
                    <p class="list__attribute attribute">
                        <span class="attribute__name">
                            {{ __('accrual.page.employees.field.salary') }}:
                        </span>
                        <span class="attribute__value rub">
                            {{ moneyFormat($accrual->getSalary()) }}
                        </span>
                    </p>
                    <p class="list__attribute attribute">
                        <span class="attribute__name">
                            {{ __('accrual.page.employees.field.fine') }}:
                        </span>
                        <span class="attribute__value rub">
                            {{ moneyFormat($accrual->getFine()) }}
                        </span>
                    </p>
                    <p class="list__attribute attribute">
                        <span class="attribute__name">
                            {{ __('accrual.page.employees.field.result') }}:
                        </span>
                        <span class="attribute__value rub">
                            {{ moneyFormat($accrual->getResult()) }}
                        </span>
                    </p>
                    @if ($accrual->getEmployee()->isWasher())
                        <p class="list__attribute attribute">
                            <a href="{{ route('employees.washer.salaryBreakdown', $employeeId) }}" class="attribute__name">
                                {{ __('accrual.detailed') }}
                            </a>
                        </p>
                    @endif
                </div>
            @empty
                <div class="p-3">
                    {{ __('accrual.page.employees.notExist') }}
                </div>
            @endforelse
        </div>

        <div class="container">
            <div class="row justify-content-center">
                {{ $accrualCollection->getEmployees()->appends($_GET)->links() }}
            </div>
        </div>
    </div>
@endsection

resources/views/employees/accrual/personalFines.blade.php
@extends('employees.layouts.admin')


@section('content')
    @include('employees.accrual._nav')

    <div class="card">
        @include('employees.fine.personal._list', ['personalFines' => $personalFines])
    </div>
@endsection

resources/views/employees/accrual/teamFines.blade.php
@extends('employees.layouts.admin')


@section('content')
    @include('employees.accrual._nav')

    <div class="card">
        @include('employees.fine.team._list', ['teamFines' => $teamFines])
    </div>
@endsection