routes/web.php
<?php



Route::get('/', function () {
    dd(1);
});

Route::get('/', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('/', 'Auth\LoginController@login');
Route::post('/logout', 'Auth\LoginController@logout')->name('logout');

Route::group(
    [
        'prefix' => 'employees',
        'as' => 'employees.',
        'namespace' => 'Employees',
        'middleware' => ['auth', 'mustByActive'],
    ],
    function () {
        Route::get('/contract/autocomplete', 'ContractController@autocomplete')->name('contract.autocomplete');
        Route::get('/client/autocomplete', 'ClientController@autocomplete')->name('client.autocomplete');
        Route::get('/car/autocomplete', 'CarController@autocomplete')->name('car.autocomplete');
        Route::get('/car-model', 'CarModelController@byMark')->name('carModel.byMark');

        Route::group(
            [
                'prefix' => 'discount-card',
                'as' => 'discountCard.',
            ],
            function () {
                Route::get('', 'DiscountCardController@list')->name('list');
                Route::get('/create', 'DiscountCardController@createForm')->name('create');
                Route::post('/create', 'DiscountCardController@create');
                Route::get('/check', 'DiscountCardController@check')->name('check');

                Route::get('/{discountCard}/edit', 'DiscountCardController@editForm')->name('edit');
                Route::put('/{discountCard}/edit', 'DiscountCardController@edit');
                Route::get('/{discountCard}/edit-disc', 'DiscountCardController@editDiscForm')->name('editDisc');
                Route::put('/{discountCard}/edit-disc', 'DiscountCardController@editDisc');

                Route::get('/{discountCard}', 'DiscountCardController@show')->name('show');
            }
        );

        Route::group(
            [
                'prefix' => 'cafe',
                'as' => 'cafe.'
            ],
            function () {
                Route::get('/sale', 'CafeController@createSaleForm')->name('createSale');
                Route::post('/sale', 'CafeController@createSale');
            }
        );

        Route::group(
            [
                'prefix' => 'order',
                'as' => 'order.',
                'namespace' => 'Order',
            ],
            function () {
                Route::get('', 'OrderController@list')->name('list');

                Route::get('/service-history', 'ServiceHistoryController@list')->name('serviceHistory');

                Route::get('/check-new-order', 'PaymentController@checkNewOrder')->name('checkNewOrder');
                Route::get('/user-register', 'ClientRegisterController@registerForm')->name('clientRegister');
                Route::post('/user-register', 'ClientRegisterController@register');

                Route::get('/{car}/{client}/ordering', 'OrderingController@orderingForm')->name('ordering');
                Route::post('/{car}/{client}/ordering', 'OrderingController@ordering');

                Route::get('/{order}', 'OrderingController@show')->name('show');

                Route::get('/{order}/edit-works', 'OrderingController@editWorksForm')->name('editWorks');
                Route::patch('/{order}/edit-works', 'OrderingController@editWorks');

                Route::patch('/{order}/admin-comment', 'OrderingController@comment')->name('adminComment');

                Route::get('/list/payment', 'PaymentController@list')->name('payment.list');
                Route::get('/{order}/payment', 'PaymentController@paymentForm')->name('payment');
                Route::post('/{order}/payment', 'PaymentController@payment');
                Route::put('/{order}/repayment', 'PaymentController@repayment')->name('repayment');
                Route::post('/{order}/payment-refusal', 'PaymentController@refusal')->name('paymentRefusal');

                Route::get('/list/overdrive', 'OverdriveController@list')->name('overdrive.list');
                Route::get('/{order}/appoint-team', 'AppointTeamController@appointTeamForm')->name('appointTeam');
                Route::patch('/{order}/appoint-team', 'AppointTeamController@appointTeam');

                Route::get('/{order}/reassign-team', 'AppointTeamController@reassignTeamForm')->name('reassignTeam');
                Route::patch('/{order}/reassign-team', 'AppointTeamController@reassignTeam');

                Route::patch('/{order}/comment', 'PaymentController@comment')->name('comment');

                Route::get('/{order}/fine', 'FineController@createForm')->name('createFine');
                Route::post('/{order}/fine', 'FineController@create');

                Route::get('/{order}/cross', 'FineController@crossForm')->name('cross');
                Route::post('/{order}/cross', 'FineController@cross');

                Route::patch('/{order}/executed', 'OrderingController@executed')->name('executed');

                Route::get('/fine/{fine}/disable', 'FineController@disableForm')->name('disableFine');
                Route::put('/fine/{fine}/disable', 'FineController@disable');
            }
        );

        Route::group(
            [
                'prefix' => 'teams',
                'as' => 'teams.',
            ],
            function () {
                Route::get('', 'TeamController@list')->name('list');
                Route::get('/create', 'TeamController@createForm')->name('create');
                Route::post('/create', 'TeamController@create');
                Route::get('/{team}', 'TeamController@show')->name('show');
                Route::get('/{team}/edit', 'TeamController@editForm')->name('edit');
                Route::put('/{team}/edit', 'TeamController@edit');
                Route::delete('/{team}/delete', 'TeamController@delete')->name('delete');
            }
        );

        Route::group(
            [
                'prefix' => 'balance',
                'as' => 'balance.',
            ],
            function () {
                Route::get('', 'BalanceController@common')->name('common');
            }
        );

        Route::group(
            [
                'prefix' => 'accrual',
                'as' => 'accrual.',
                'namespace' => 'Accrual',
            ],
            function () {
                Route::get('', 'AccrualController@common')->name('common');
                Route::get('personal-fine', 'PersonalFineController@list')->name('personalFines');
                Route::get('team-fine', 'TeamFineController@list')->name('teamFines');
                Route::get('employees', 'EmployeesController@list')->name('employees');
            }
        );

        Route::group(
            [
                'prefix' => 'washer',
                'as' => 'washer.',
                'namespace' => 'Washer',
            ],
            function () {
                Route::get('', 'WasherController@list')->name('list');
                Route::get('/{user}', 'WasherController@show')->name('show');

                Route::get('/{user}/fine', 'PersonalFineController@createForm')->name('createFine');
                Route::post('/{user}/fine', 'PersonalFineController@create');

                Route::get('/personal-fine/{fine}', 'PersonalFineController@show')->name('showPersonalFine');
                Route::get('/personal-fine/{fine}/disable', 'PersonalFineController@disableForm')->name('disablePersonalFine');
                Route::put('/personal-fine/{fine}/disable', 'PersonalFineController@disable');
                Route::get('/{user}/personal-fines', 'PersonalFineController@list')->name('personalFines');
                Route::get('/{user}/team-fines', 'TeamFineController@list')->name('teamFines');
                Route::get('/{user}/salary-breakdown', 'SalaryBreakdownController@index')->name('salaryBreakdown');
            }
        );
    }
);

Route::group(
    [
        'prefix' => 'super_admin',
        'as' => 'superAdmin.',
        'namespace' => 'SuperAdmin',
        'middleware' => ['auth', 'mustByActive', App\Http\Middleware\SuperAdmin::class],
    ],
    function () {
        Route::get('/', 'HomeController@index')->name('home');

        Route::group(
            [
                'prefix' => 'fine',
                'as' => 'fine.',
                'namespace' => 'Fine',
            ],
            function () {
                Route::get('payment-refusal-fine-size', 'PaymentRefusalFineSizeController@form')->name('paymentRefusalFineSize');
                Route::put('payment-refusal-fine-size', 'PaymentRefusalFineSizeController@change');
            }
        );

        Route::group(
            [
                'prefix' => 'service_center',
                'as' => 'serviceCenter.'
            ],
            function () {
                Route::get('', 'ServiceCentersController@list')->name('list');
                Route::get('/create', 'ServiceCentersController@createForm')->name('create');
                Route::post('/create', 'ServiceCentersController@create');
                Route::get('/{serviceCenter}', 'ServiceCentersController@show')->name('show');
                Route::get('/{serviceCenter}/edit', 'ServiceCentersController@editForm')->name('edit');
                Route::put('/{serviceCenter}/edit', 'ServiceCentersController@edit');
                Route::delete('/{serviceCenter}/delete', 'ServiceCentersController@delete')->name('delete');
            }
        );

        Route::group(
            [
                'prefix' => 'car_wash',
                'as' => 'carWash.',
                'namespace' => 'CarWash',
            ],
            function () {
                Route::group(
                    [
                        'prefix' => 'works',
                        'as' => 'works.',
                    ],
                    function () {
                        Route::get('', 'WorksController@index')->name('list');

app/Http/Controllers/Employees/Accrual/AccrualController.php
<?php

namespace App\Http\Controllers\Employees\Accrual;

use App\Entity\ServiceCenter;
use App\Entity\User\Role;
use App\Entity\User\User;
use App\Http\Controllers\Controller;
use App\Services\AccrualService;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class AccrualController extends Controller
{
    public function __construct()
    {
        $this->middleware(['auth', 'can:manage-accrual']);
    }

    public function common()
    {
        $pageTitle = trans('accrual.page.common.header');
        $commonAccrual = $this->getService()->common();

        return view('employees.accrual.common', compact('pageTitle', 'commonAccrual'));
    }

    private function getService(): AccrualService
    {
        /** @var User $user */
        $user = Auth::user();
        /** @var ServiceCenter $serviceCenter */
        $serviceCenter = $user->serviceCenter;
        return new AccrualService($serviceCenter);
    }
}

app/Http/Controllers/Employees/Accrual/EmployeesController.php
<?php

namespace App\Http\Controllers\Employees\Accrual;

use App\Entity\ServiceCenter;
use App\Entity\User\Role;
use App\Entity\User\User;
use App\Http\Controllers\Controller;
use App\Services\AccrualService;
use App\Services\Dto\DateRangeDto;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class EmployeesController extends Controller
{
    public function __construct()
    {
        $this->middleware(['auth', 'can:manage-accrual']);
    }

    public function list(Request $request)
    {
        $pageTitle = trans('accrual.page.employees.header');
        $dataRange = new DateRangeDto($request->get('range'));
        $accrualCollection = $this->getService()->employeesSalary($dataRange, Auth::user());

        return view('employees.accrual.employees', compact('pageTitle', 'accrualCollection', 'dataRange'));
    }

    private function getService(): AccrualService
    {
        /** @var User $user */
        $user = Auth::user();
        /** @var ServiceCenter $serviceCenter */
        $serviceCenter = $user->serviceCenter;
        return new AccrualService($serviceCenter);
    }
}

app/Http/Controllers/Employees/Accrual/PersonalFineController.php
<?php

namespace App\Http\Controllers\Employees\Accrual;

use App\Entity\ServiceCenter;
use App\Entity\User\Fine\PersonalFine;
use App\Entity\User\User;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;

class PersonalFineController extends Controller
{
    public function __construct()
    {
        $this->middleware(['auth', 'can:manage-personal-fines']);
    }

    public function list()
    {
        $pageTitle = trans('personalFine.page.list.header');

        /** @var User $user */
        $user = Auth::user();
        /** @var ServiceCenter $serviceCenter */
        $serviceCenter = $user->serviceCenter;
        $personalFines = PersonalFine::with(['user', 'user.serviceCenter'])->byServiceCenter($serviceCenter)->orderByDesc('id')->paginate(20);

        return view('employees.accrual.personalFines', compact('pageTitle', 'personalFines'));
    }
}

app/Http/Controllers/Employees/Accrual/TeamFineController.php
<?php

namespace App\Http\Controllers\Employees\Accrual;

use App\Entity\ServiceCenter;
use App\Entity\User\Fine\TeamFine;
use App\Entity\User\User;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;

class TeamFineController extends Controller
{
    public function __construct()
    {
        $this->middleware(['auth', 'can:manage-team-fines']);
    }

    public function list()
    {
        $pageTitle = trans('personalFine.page.list.header');

        /** @var User $user */
        $user = Auth::user();
        /** @var ServiceCenter $serviceCenter */
        $serviceCenter = $user->serviceCenter;

        $teamFines = TeamFine::with('users', 'order')->byServiceCenter($serviceCenter)->orderByDesc('id')->paginate(20);

        return view('employees.accrual.teamFines', compact('pageTitle', 'teamFines'));
    }
}

app/Http/Controllers/Employees/BalanceController.php
<?php

namespace App\Http\Controllers\Employees;

use App\Entity\User\User;
use App\Http\Controllers\Controller;
use App\Services\BalanceService;
use App\Services\Dto\DateRangeLastMonthDto;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class BalanceController extends Controller
{
    public function __construct()
    {
        $this->middleware(['auth', 'can:manage-balance']);
    }

    public function common(Request $request)
    {
        $pageTitle = trans('balance.page.common.header');

        /** @var User $user */
        $user = Auth::user();
        $service = new BalanceService($user->serviceCenter);

        $dataRange = new DateRangeLastMonthDto($request->get('range'));
        $balance = $service->common(
            $dataRange,
            $request->get('payment'),
            $request->get('point'),
            count($request->only(['range', 'payment', 'point'])) == 0
        );


        return view('employees.balance.common', compact('pageTitle', 'balance', 'dataRange'));
    }
}

app/Http/Controllers/Employees/CafeController.php
<?php

namespace App\Http\Controllers\Employees;

use App\Entity\Cafe\Sale;
use App\Entity\Cafe\SaleType;
use App\Entity\User\User;
use App\Http\Controllers\Controller;
use App\Http\Requests\Cafe\CreateSaleRequest;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class CafeController extends Controller
{
    public function __construct()
    {
        $this->middleware(['auth', 'can:manage-sale-cafe']);
    }

    public function createSaleForm(Request $request)
    {
        $pageTitle = trans('cafe.page.createSale.header');

        $saleTypes = SaleType::active()->orderBy('name')->orderBy('id')->get();
        $sale = new Sale();

        return view('employees.cafe.createSale', compact('pageTitle', 'saleTypes', 'sale'));
    }

    public function createSale(CreateSaleRequest $request)
    {
        /** @var User $user */
        $user = Auth::user();
        Sale::register(
            $request->get('sum'),
            $request->get('sale-type'),
            $request->get('payment-type'),
            $user,
            $user->serviceCenter
        );

        return redirect()
            ->to(route('employees.cafe.createSale'))
            ->with('success', trans('cafe.message.successCreateSale'));
    }
}

app/Http/Controllers/Employees/CarController.php
<?php

namespace App\Http\Controllers\Employees;

use App\Entity\Car;
use App\Http\Controllers\Controller;
use App\Http\Resources\CarAutocomplete;
use Illuminate\Http\Request;

class CarController extends Controller
{
    public function __construct()
    {
        $this->middleware(['auth', 'can:manage-order']);
    }

    public function autocomplete(Request $request)
    {
        $value = $request->get('value');
        $cars = Car::with('clients', 'carModel', 'carModel.mark')
            ->where('number', 'like', $value . '%')
            ->limit(20)
            ->get();

        return CarAutocomplete::collection($cars);
    }
}

app/Http/Controllers/Employees/CarModelController.php
<?php

namespace App\Http\Controllers\Employees;

use App\Entity\Car;
use App\Entity\CarModel;
use App\Http\Controllers\Controller;
use App\Http\Resources\CarModel as CarModelResources;
use Illuminate\Http\Request;

class CarModelController extends Controller
{
    public function __construct()
    {
        $this->middleware(['auth', 'can:manage-order']);
    }

    public function byMark(Request $request)
    {
        $markId = intval($request->get('mark'));

        $carModels = CarModel::forMark($markId)->get();

        return CarModelResources::collection($carModels);
    }
}

resources/views/employees/teams/_employee.blade.php
{{ $employee->getFio()->getFullName() }}
@if ($employee->service_center_id == Auth::user()->service_center_id)
    <sup>
        <span class="badge badge-success">{{ __('team.field.our') }}</span>
    </sup>
@elseif (isset($employee->service_center_id))
    <sup>
        <span class="badge badge-warning">{{ $employee->serviceCenter->name }}</span>
    </sup>
@endif

resources/views/employees/teams/_employeeList.blade.php
@foreach ($employees as $employe)
    <p>
        <input autocomplete="off" type="checkbox" name="employees[]" value="{{ $employe->id }}" {{ in_array($employe->id, old('employees', $employeesIds)) ? ' checked' : '' }}>
        <label class="mb-0">
            @include('employees.teams._employee', ['employee' => $employe])
            @if ($employe->getTeam() !== null)
                <br>
                <a href="{{ route('employees.teams.show', $employe->getTeam()) }}" class="attribute__value small">
                    {{ $employe->getTeam()->name }}
                </a>
            @endif
        </label>

    </p>
@endforeach

resources/views/employees/teams/_employees.blade.php
<div class="col-md-6">
    <div class="team-employees-list">
        <p class="team-employees-list__header">{{ __('team.sep.our') }}</p>
        <div class="team-employees-list__our">
            @include('employees.teams._employeeList', ['employeesIds' => $employeesIds, 'employees' => $employees->getOur()])
        </div>

        <p class="team-employees-list__header">{{ __('team.sep.foreign') }}</p>
        <div class="team-employees-list__foreign">
            @include('employees.teams._employeeList', ['employeesIds' => $employeesIds, 'employees' => $employees->getForeign()])
        </div>
    </div>

    @if ($errors->has('employees'))
        <span class="invalid-feedback d-block">
            <strong>{{ $errors->first('employees') }}</strong>
        </span>
    @elseif ($errors->has('employees.*'))
        <span class="invalid-feedback d-block">
            <strong>{{ $errors->first('employees.*') }}</strong>
        </span>
    @endif
</div>

resources/views/employees/teams/_form.blade.php
<div class="form-group row">
    <label for="name" class="col-md-4 col-form-label text-md-right">
        {{ __('team.field.name') }}<sup class="text-danger">*</sup>
    </label>

    <div class="col-md-6">
        <input id="name" type="text" class="form-control{{ $errors->has('name') ? ' is-invalid' : '' }}" name="name" value="{{ old('name', $team->name) }}" required>

        @if ($errors->has('name'))
            <span class="invalid-feedback">
                <strong>{{ $errors->first('name') }}</strong>
            </span>
        @endif
    </div>
</div>

<div class="form-group row">
    <label for="employees" class="col-md-4 col-form-label text-md-right">
        {{ __('team.field.availableEmployees') }}<sup class="text-danger">*</sup>
    </label>

    @include('employees.teams._employees', ['employees' => $employees, 'employeesIds' => array_pluck($team->employees, 'id')])
</div>

<div class="form-group row mb-0">
    <div class="col-md-6 offset-md-4">
        <button type="submit" class="btn btn-primary">
            {{ $buttonTitle }}
        </button>
    </div>
</div>

resources/views/employees/teams/_nav.blade.php
<ul class="nav nav-tabs mb-3">
    @can ('manage-teams')
        <li class="nav-item">
            <a class="nav-link {{ Route::currentRouteNamed('employees.teams.list') ? 'active' : '' }}" href="{{ route('employees.teams.list') }}">
                {{ __('navbar.employees.teams') }}
            </a>
        </li>
    @endcan
    @can ('manage-washers')
        <li class="nav-item">
            <a class="nav-link {{ Route::currentRouteNamed('employees.washer.list') ? 'active' : '' }}" href="{{ route('employees.washer.list') }}">
                {{ __('navbar.employees.washers') }}
            </a>
        </li>
    @endcan
</ul>

resources/views/employees/teams/_washersList.blade.php
@foreach($washers as $washer)
    <div class="list__item">
        <p class="list__header">
            <a href="{{ route('employees.washer.show', $washer) }}">
                @include('employees.teams._employee', ['employee' => $washer])
            </a>
        </p>
        <p class="list__attribute attribute">
            <span class="attribute__name">
                {{ __('user.field.phones') }}:
            </span>
            <span class="attribute__value">
                {!! phonesFormat($washer->phones, true) !!}
            </span>
        </p>

        @if ($washer->getTeam() !== null)
            <p class="list__attribute attribute">
                <span class="attribute__name">
                    {{ __('user.field.team') }}:
                </span>
                <a href="{{ route('employees.teams.show', $washer->getTeam()) }}" class="attribute__value">
                    {{ $washer->getTeam()->name }}
                </a>
            </p>
        @endif

        @if ($showCurrentServiceCenter && !$washer->currentEqualConstantServiceCenter() && $washer->getCurrentServiceCenter() !== null)
            <p class="list__attribute attribute">
                <span class="attribute__name">
                    {{ __('user.field.currentServiceCenter') }}:
                </span>
                <span class="attribute__value">
                    {{ $washer->getCurrentServiceCenter()->name }}
                </span>
            </p>
        @endif
    </div>
@endforeach

resources/views/employees/teams/create.blade.php
@extends('employees.layouts.admin')

@section('content')
    <div class="card">
        <div class="card-header">
            {{ $pageTitle }}
        </div>
        <div class="card-body">
            <div class="row">
                <div class="col-md-6 offset-md-4">
                    @include('partials.form.markerRequireFields')
                </div>
            </div>

            <form method="POST" action="">
                @csrf
                @include('employees.teams._form', ['team' => $team, 'employees' => $employees, 'buttonTitle' => __('team.action.create')])
            </form>
        </div>
    </div>
@endsection

resources/views/employees/teams/edit.blade.php
@extends('employees.layouts.admin')

@section('content')
    <div class="card">
        <div class="card-header">
            {{ $pageTitle }}
        </div>
        <div class="card-body">
            <div class="row">
                <div class="col-md-6 offset-md-4">
                    @include('partials.form.markerRequireFields')
                </div>
            </div>

            <form method="POST" action="">
                @csrf
                @method("PUT")
                @include('employees.teams._form', ['team' => $team, 'employees' => $employees, 'buttonTitle' => __('team.action.edit')])
            </form>
        </div>
    </div>
@endsection

resources/views/employees/teams/list.blade.php
@extends('employees.layouts.admin')

@section('content')
    @include('employees.teams._nav')

    <p>
        <a href="{{ route('employees.teams.create') }}" class="btn btn-success">
            {{ __('team.action.create') }}
        </a>
    </p>

    <div class="card">
        <div class="list">
            @forelse($teams as $team)
                <div class="list__item">
                    <p class="list__header">
                        <a href="{{ route('employees.teams.show', $team) }}">{{ $team->name }}</a>
                    </p>
                    <p class="list__attribute attribute">
                        <span class="attribute__name">
                            {{ __('team.field.employees') }}:
                        </span>
                        <span class="attribute__value">
                            {{ listEmployees($team->employees) }}
                        </span>
                    </p>
                </div>
            @empty
                <div class="p-3">
                    {{ __('team.notExist') }}
                </div>
            @endforelse
        </div>
    </div>
@endsection

resources/views/employees/teams/show.blade.php
@extends('employees.layouts.admin')


@section('content')

    <div class="d-flex flex-row mb-3">
        @if (!$team->isTemporary())
            <a href="{{ route('employees.teams.edit', ['team' => $team]) }}" class="btn btn-success mr-1">
                {{ __('team.action.edit') }}
            </a>
        @endif

        <button class="btn btn-danger" data-toggle="modal" data-target="#confirmDelete">
            {{ __('team.action.delete') }}
        </button>
        @include(
            'partials.modal.confirm',
            [
                'target' => "confirmDelete",
                'body' => __('team.confirm.delete', ['num' => $team->id]),
                'action' => route('employees.teams.delete', ['team' => $team]),
                'method' => 'DELETE'
            ]
        )
    </div>

    <div class="card">
        <div class="card-body">
            <div>
                <p><strong>{{ __('team.field.name') }}: </strong>{{ $team->name }}</p>
                <p><strong>{{ __('team.field.employees') }}:<br></strong>{{ listEmployees($team->employees) }}</p>
            </div>
        </div>
    </div>
@endsection

resources/views/employees/teams/washers.blade.php
@extends('employees.layouts.admin')

@section('content')
    @include('employees.teams._nav')

    <div class="card">
        <div class="list">

            @if(! $washers->isOurEmpty())
                <div class="list__row">
                    <p>{{ __('team.sep.our') }}</p>
                </div>

                @include('employees.teams._washersList', ['washers' => $washers->getOur(), 'showCurrentServiceCenter' => 0])
            @endif

            @if(! $washers->isForeignEmpty())
                <div class="list__row">
                    <p>{{ __('team.sep.foreign') }}</p>
                </div>

                @include('employees.teams._washersList', ['washers' => $washers->getForeign(), 'showCurrentServiceCenter' => 1])
            @endif

            @if ($washers->isEmpty())
                <div class="p-3">
                    {{ __('washer.notExist') }}
                </div>
            @endif
        </div>
    </div>
@endsection